on:
  push:
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'
      - '**.json'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
    paths:
      - '**.go'
      - '**.yaml'
      - '**.yml'
      - '**.json'
      - 'go.mod'
      - 'go.sum'

name: unit tests
jobs:
  test:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Vet
      run: go vet ./...

    - name: Code Coverage
      run: go test ./... -timeout 600s -race -count=1 -covermode=atomic -coverprofile=coverage.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
        fail_ci_if_error: false
        verbose: false